config/routes.rb
Rails.application.routes.draw do
  root 'events#calendar'
  resources :events
  get 'my_events', to: 'events#my_events'
  get 'new_algorithms', to: 'algorithms#new'
  get 'algorithms/(:number)', to: 'algorithms#display', as: :algorithms

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  match '/signup',  to: 'users#new',        via: 'get'
  match '/signin',  to: 'sessions#new',     via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/views/layouts/_display_user.html.haml
.user_position
  - if signed_in?
    = link_to current_user.email, edit_user_path(current_user), id: "position1"
    = link_to "Sign out", signout_path, method: "delete", id: "position2"
  - else
    = link_to "Sign in", signin_path, id: "position1"
    = link_to "Sign up", new_user_path, id: "position2"

app/views/layouts/_flash.html.haml
- flash.each do |type, message|
  %div{ class: "alert #{bootstrap_flash_class(type)} fade in" }
    = message
    %button.close{ data: { dismiss: 'alert' } }

app/views/layouts/_header.html.haml
#logo
  = link_to root_path do
    = image_tag "download.png"
#algorithm
  = link_to "Algorithm", new_algorithms_path
#menu_head
  .dropdown
    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}

      - if signed_in?
        - if current_user.admin?
          Admin menu
          %span.caret
        - else
          Menu
          %span.caret
    - if signed_in?
      - if current_user.admin?
        %ul.dropdown-menu{role: "menu"}
          %li= link_to "New event", new_event_path
          %li= link_to "Show events"
          %li= link_to "Calendar", root_path
      - else
        %ul.dropdown-menu{role: "menu"}
          %li= link_to "New event", new_event_path
          %li= link_to "Calendar", root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title OnlineBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .header
      .block_head
        = render 'layouts/header'
      = render 'layouts/display_user'
    .content
      = render 'layouts/flash'
      = yield